// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtFSjv1s6CrSj6E40ErKoK_N4Y4dPuaNw',
    appId: '1:622741006656:web:300d6906f0ee077af8f2a5',
    messagingSenderId: '622741006656',
    projectId: 'herppro-76ded',
    authDomain: 'herppro-76ded.firebaseapp.com',
    storageBucket: 'herppro-76ded.firebasestorage.app',
    measurementId: 'G-G9PQ3VKQ05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnJK7dcT5QtOHxNJ6gX0xl2YqoT7c6s50',
    appId: '1:622741006656:android:870ac626a24b4faaf8f2a5',
    messagingSenderId: '622741006656',
    projectId: 'herppro-76ded',
    storageBucket: 'herppro-76ded.firebasestorage.app',
  );
}
